### Registro de Usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "Ricardo",
    "email": "ricardo@email.com",
    "password": "contraseña",
    "age": 20,
    "city": "Madrid",
    "interests": ["tecnología", "música"]
}

### Login de Usuario
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "ricardo@email.com",
    "password": "contraseña"
}

### Actualizar Perfil de Usuario
PUT http://localhost:3000/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzNjE3ZDFmZWI2YzFjNzg0ODQ5ZDIiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMTQyMDU0MSwiZXhwIjoxNzMxNDU2NTQxfQ.wc9kEXrnXx8CJsTdBVjFQMA_NUn3J3T0nS38keuv3es

{
    "name": "ricardo2",
    "email": "ricardo2@example.com",
    "age": 30,
    "city": "Nueva Ciudad"
}

###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "ricardo2@example.com",
    "password": "contraseña"
}

### Eliminar Perfil de Usuario
DELETE http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzIyNGFjZTg3Y2ZkZjVjZTgzZTM4YTMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzMwMzAwNzI2LCJleHAiOjE3MzAzMDc5MjZ9.WQGKUAzKUiFrLAVXxGIV99ubxwJZ7WzL3taUEM9vdsA

### Crear comercio
POST http://localhost:3000/api/commerce/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzNjE3ZDFmZWI2YzFjNzg0ODQ5ZDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzE0MjA3NDAsImV4cCI6MTczMTQ1Njc0MH0.z-MkuIQesog_8HxX3T_WCV28FW_2w55_QgHuZSTWo0c

{
    "name": "Comercio_final",
    "cif": "123456788",
    "email": "comerciofinal@example.com",
    "phone": "123456788",
    "address": "Dirección del Comercio"
}

### Ver comercio
GET http://localhost:3000/api/commerce/123456788
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzE0MjA4MDksImV4cCI6MTczMTQ1NjgwOX0.b-31vlXmHdcNB3QtOB156zhiS13frOQKrpi1ymi7Ibs

### Actualizar comercio
PUT http://localhost:3000/api/commerce/123456788
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM

{
    "name": "ejemplo 10000000",
    "email": "nuevoemail1000@example.com",
    "phone": "123456784",
    "address": "mostoles central"
}

### Eliminar comercio
DELETE http://localhost:3000/api/commerce/987654321
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM

### WEBS


### Obtener una página web por id
GET http://localhost:3000/api/webCommerce

### Crear una nueva página web
POST http://localhost:3000/api/webCommerce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzE0MjA4MDksImV4cCI6MTczMTQ1NjgwOX0.b-31vlXmHdcNB3QtOB156zhiS13frOQKrpi1ymi7Ibs
Content-Type: application/json

{
    "city": "Badajoz",
    "activity": "tecnología",
    "title": "Página Web de Tecnología",
    "summary": "Esta es una página dedicada a las últimas noticias y avances en tecnología.",
    "texts": [
        "Texto 1 sobre tecnología.",
        "Texto 2 sobre tecnología."
    ],
    "images": [],
    "reviews": {
        "scoring": 4,
        "totalRatings": 10,
        "reviewTexts": [
            "Gran página, muy informativa.",
            "Me encanta el contenido que ofrecen."
        ]
    }
}

### Actualizar una página web por id
PUT http://localhost:3000/api/webCommerce/673363361feb6c1c784849e4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzE0MjA4MDksImV4cCI6MTczMTQ1NjgwOX0.b-31vlXmHdcNB3QtOB156zhiS13frOQKrpi1ymi7Ibs
Content-Type: application/json

{
    "field1": "nuevo valor 1",
    "field2": "nuevo valor 2"
    // Otros campos a actualizar
}

### Eliminar una página web (borrado logico)
DELETE http://localhost:3000/api/webCommerce/6723b70a273671525e77cc61?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM

### Borrado fisico
DELETE http://localhost:3000/api/webCommerce/6723b70a273671525e77cc61
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM

### Subir imagen
### PATCH para postear una imagen vinculada a la web
PATCH http://localhost:3000/api/webCommerce/6723b70a273671525e77cc61/upload
Content-Type: multipart/form-data; boundary=Boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzE0MjA4MDksImV4cCI6MTczMTQ1NjgwOX0.b-31vlXmHdcNB3QtOB156zhiS13frOQKrpi1ymi7Ibs

--Boundary
Content-Disposition: form-data; name="image"; filename="travis.jpg"
Content-Type: image/jpeg

< ./example.jpg
--Boundary--

### Ver emails 
GET http://localhost:3000/api/webCommerce/6723b70a273671525e77cc61/interested?interests=tecnología
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM
