### Registro de Usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "Ricardo",
    "email": "ricardo@email.com",
    "password": "contraseña",
    "age": 20,
    "city": "Madrid",
    "interests": ["tecnología", "música"]
}

### Login de Usuario
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "ricardo@email.com",
    "password": "contraseña"
}

### Actualizar Perfil de Usuario
PUT http://localhost:3000/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzNjE3ZDFmZWI2YzFjNzg0ODQ5ZDIiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMTQyMDU0MSwiZXhwIjoxNzMxNDU2NTQxfQ.wc9kEXrnXx8CJsTdBVjFQMA_NUn3J3T0nS38keuv3es

{
    "name": "ricardo2",
    "email": "ricardo2@example.com",
    "age": 30,
    "city": "Nueva Ciudad"
}

###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "ricardo2@example.com",
    "password": "contraseña"
}

### Eliminar Perfil de Usuario
DELETE http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzIyNGFjZTg3Y2ZkZjVjZTgzZTM4YTMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzMwMzAwNzI2LCJleHAiOjE3MzAzMDc5MjZ9.WQGKUAzKUiFrLAVXxGIV99ubxwJZ7WzL3taUEM9vdsA

### Crear comercio
POST http://localhost:3000/api/commerce/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzNjE3ZDFmZWI2YzFjNzg0ODQ5ZDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzE0MjI5NDksImV4cCI6MTczMTQ1ODk0OX0.Rq-9rNJ00JfxqgmTwnvftP-C86Iy6S9foKkxrQtwbD0

{
    "name": "Comercio_final2",
    "cif": "123456787",
    "email": "comerciofinal2@example.com",
    "phone": "123456787",
    "address": "Dirección del Comercio"
}

### Ver comercio
GET http://localhost:3000/api/commerce/123456787
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzNjE3ZDFmZWI2YzFjNzg0ODQ5ZDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzE0NTkzNjgsImV4cCI6MTczMTQ5NTM2OH0.iQyF6xeKArSkVZbL4S0fvudWjmZvrfm9KYJhEsyV8oM

### Actualizar comercio
PUT http://localhost:3000/api/commerce/123456788
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM

{
    "name": "ejemplo 10000000",
    "email": "nuevoemail1000@example.com",
    "phone": "123456784",
    "address": "mostoles central"
}

### Eliminar comercio
DELETE http://localhost:3000/api/commerce/987654321
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM

### WEBS

### Ver todas las webs
GET http://localhost:3000/api/webCommerce

### Ver una web por su id
GET http://localhost:3000/api/webCommerce/6733ebefc16f379f5f4ce4ff

### Crear una nueva página web
POST http://localhost:3000/api/webCommerce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzE0MjI5ODQsImV4cCI6MTczMTQ1ODk4NH0.ms9SV3xgaidKR_hoHtotFPecEO0l9og0V542CkQgc6U
Content-Type: application/json

{
   "city": "Barcelona",
   "activity": "deporte",
   "title": "Página Web de Deportes y Ejercicio",
   "summary": "Una página enfocada en ofrecer consejos y rutinas de ejercicios para mejorar tu rendimiento físico.",
   "texts": [
      "Consejo 1: Realiza entrenamientos de fuerza para mejorar tu resistencia.",
      "Consejo 2: La nutrición adecuada es esencial para un buen rendimiento deportivo."
   ],
   "images": [],
   "reviews": {
      "scoring": 5,
      "totalRatings": 20,
      "reviewTexts": [
         "Muy útil para mantenerme motivado a hacer ejercicio.",
         "Excelente página, con rutinas de ejercicio muy variadas."
      ]
   }
}

### Actualizar una página web por id
PUT http://localhost:3000/api/webCommerce/6733725d1e5c163c8a43a966
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzE0MjA4MDksImV4cCI6MTczMTQ1NjgwOX0.b-31vlXmHdcNB3QtOB156zhiS13frOQKrpi1ymi7Ibs
Content-Type: application/json

{
    "city": "Madrid",
    "title": "Página Web de Innovación Tecnológica"
}


### Eliminar una página web (borrado logico)
DELETE http://localhost:3000/api/webCommerce/6723b70a273671525e77cc61?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM

### Borrado fisico
DELETE http://localhost:3000/api/webCommerce/6723b70a273671525e77cc61
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzAzODY1ODksImV4cCI6MTczMDQyMjU4OX0.SNTK6aYR25fSe3X4joWnZsEhiFM6ykeUVxQImHK9JTM

### Subir imagen
### PATCH para postear una imagen vinculada a la web
PATCH http://localhost:3000/api/webCommerce/6733725d1e5c163c8a43a966
Content-Type: multipart/form-data; boundary=Boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzMzNjE3ZDFmZWI2YzFjNzg0ODQ5ZDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzE0NTkzNjgsImV4cCI6MTczMTQ5NTM2OH0.iQyF6xeKArSkVZbL4S0fvudWjmZvrfm9KYJhEsyV8oM

--Boundary
Content-Disposition: form-data; name="image"; filename="travis.jpg"
Content-Type: image/jpg

< ./travis.jpg
--Boundary--
>

### Ver emails
GET http://localhost:3000/api/webCommerce/6733725d1e5c163c8a43a966/interested?interests=tecnología
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzE0MjA4MDksImV4cCI6MTczMTQ1NjgwOX0.b-31vlXmHdcNB3QtOB156zhiS13frOQKrpi1ymi7Ibs
